# 1.Port 80 (HTTP) configuration to redirect all traffic to HTTPS
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html

    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule ^(.*)$ https://localhost:8443%{REQUEST_URI} [L,R=301]
</VirtualHost>

# 2. Port 443 (HTTPS) configuration with SSL and error documents, plus security rules to block access to sensitive files
<VirtualHost *:443>
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html


    SSLEngine on
    SSLCertificateFile /etc/ssl/certs/apache-selfsigned.crt
    SSLCertificateKeyFile /etc/ssl/private/apache-selfsigned.key


    ErrorDocument 404 /404.php
    ErrorDocument 500 /500.php

    <Directory /var/www/html>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>


    <FilesMatch "\.(md|yml|json|lock|sql|conf|log)$|Dockerfile">
        Require all denied
    </FilesMatch>
    
    <Files "README.md">
        Require all denied
    </Files>
    
    <DirectoryMatch "^/.*/\.git/">
        Require all denied
    </DirectoryMatch>
</VirtualHost>